// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBITmicryfyzkwmDXWutxrheIWKP5kA_o4',
    appId: '1:994105757694:android:1927e645f30bf8ce01baaf',
    messagingSenderId: '994105757694',
    projectId: 'intracake',
    storageBucket: 'intracake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxy0vbSNIHl8Isdhjv_yhveWBjhI64CXo',
    appId: '1:994105757694:ios:340615ae6788f2d401baaf',
    messagingSenderId: '994105757694',
    projectId: 'intracake',
    storageBucket: 'intracake.firebasestorage.app',
    iosBundleId: 'com.example.intracake',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxsJFvymOgpmXDSUmzt4D9t3CUMLMxUxY',
    appId: '1:994105757694:web:589c3dce7a159d1a01baaf',
    messagingSenderId: '994105757694',
    projectId: 'intracake',
    authDomain: 'intracake.firebaseapp.com',
    storageBucket: 'intracake.firebasestorage.app',
    measurementId: 'G-842HH8DHEQ',
  );

}